[package]
name = "nvg"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "nvg"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
directories = "5"
owo-colors = "4"
anyhow = "1"
thiserror = "1"
webbrowser = "1"
indicatif = "0.17"

[profile.dev]
incremental = true

[profile.release]
incremental = true
